import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dappers</title>
        <meta name="description" content="Generated by Cori" />
        <link rel="icon" href="/logo.png" />
        <link
          href="https://fonts.googleapis.com/css?family=Roboto"
          rel="stylesheet"
        ></link>
      </Head>
      <div className={styles.main}>
        <div className={styles.topBar}>
          <div className={styles.logoLink}>
            <img src="favicon.png" width="22px" height="22px" />
            Dappers
          </div>
          <div className={styles.signLink}>
            <img src="avatar.png" width="20px" height="22px" />
            Sign In
          </div>
        </div>
        <div className={styles.welcomeDiv}>
          <div>
            <div className={styles.welcomeTitle}>
              WEB 3.0 AT YOUR FINGERTIPS
            </div>

            <div className={styles.description}>
              We provide you the framework to jet speed your ideas.
            </div>
            <div className={styles.linkDiv}>
              <a href="#">
                <img
                  src="/github-icon.png"
                  alt="Github Icon"
                  width={36}
                  height={36}
                />
              </a>
              <a href="#">
                <img
                  src="/discord-icon.png"
                  alt="Discord Icon"
                  width={36}
                  height={36}
                />
              </a>
              <a href="#">
                <img
                  src="/twitter-icon.png"
                  alt="Twitter Icon"
                  width={40}
                  height={36}
                />
              </a>
            </div>
          </div>
        </div>

        <div className={styles.chooseDiv}>
          <div>
            <div className={styles.welTitle}>CHOOSE FROM</div>

            <div className={styles.chooseText}>
              Launch your own decentralized crypto currency application.
            </div>
          </div>
          <div className={styles.platformDiv}>
            <Link href="/dex">
              <a>
                <Image
                  src="/dex-icon.png"
                  alt="DexIcon"
                  width={132}
                  height={141}
                />
                <div>DEX</div>
              </a>
            </Link>
            <Link href="/nftmarket">
              <a>
                <Image
                  src="/nftmarket-icon.png"
                  alt="NFTMarketIcon"
                  width={132}
                  height={141}
                />
                <div>NFT Market</div>
              </a>
            </Link>
            <Link href="/cryptogame">
              <a>
                <Image
                  src="/cryptogame-icon.png"
                  alt="CryptoGame"
                  width={132}
                  height={141}
                />
                <div>Crypto Game</div>
              </a>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
